export const endpoints = {
  machines: "/machines",
  machine: (id: string) => `/machines/${id}`,
  machineImage: (id: string) => `/machines/${id}/image`,
  machineLogs: (id: string) => `/machines/${id}/logs`,
  machineNotes: (id: string) => `/machines/${id}/notes`,
  logs: "/logs",
  alerts: "/alerts",
  alertAck: (id: string) => `/alerts/${id}/acknowledge`,
  maintenance: "/maintenance",
  maintenanceItem: (id: string) => `/maintenance/${id}`,
  metricsFleet: "/metrics/fleet",
  metricsMachine: (id: string) => `/metrics/machines/${id}`,
  audit: "/audit",
  settings: "/settings",
  reportTemplates: "/report-templates",
  reportTemplate: (id: string) => `/report-templates/${id}`,
  reportSchedules: "/report-schedules",
  reportSchedule: (id: string) => `/report-schedules/${id}`,
  chartHourly: "/charts/events/hourly",
  chartDaily: "/charts/events/daily",
  chartWeekly: "/charts/events/weekly",
  chartMonthly: "/charts/events/monthly",
  chartYearly: "/charts/events/yearly",
  machineChartEvents: (machineId: string, period: string) =>
    `/machines/${machineId}/charts/events/${period}`,
} as const;
