machines:
  - id: LMS_asservimento_DVK_3LMS-R25-PA-AU
    rdp_enabled: true
    pingable: true
    smb_host: 10.0.0.241
    smb_share: logs
    log_path: pezzi.log
    username: LMS
    password: dvk
    domain: ""
    nome_macchinario: LMS_asservimento_DVK_3LMS-R25-PA-AU
    nome_pezzo: inserimento_corpo_sifone

  - id: DVK_3W-MOA6-8C
    rdp_enabled: true
    pingable: true
    smb_host: 10.0.0.238
    smb_share: logs
    log_path: pezzi.log
    username: DVK
    password: dvk
    domain:
    nome_macchinario: DVK_3W-MOA6-8C
    nome_pezzo: lavorazione_corpo_sifone

  #- id: Logicat_verniciatura_4412023269
  #  rdp_enabled: false
  #  smb_host: 10.0.0.200
  #  smb_share: 
  #  log_path: 
  #  username: 
  #  password: 
  #  domain: ""
  #  nome_macchinario: Logicat_verniciatura_4412023269
  #  nome_pezzo: verniciatura_polvere_sifone
    #Aprire iframe del produttore

  #- id: Logicat_lavorazione_telaini_241990100
  #  rdp_enabled: false
  #  smb_host: 10.0.0.2
  #  smb_share: 
  #  log_path: 
  #  username: 
  #  password: 
  #  domain: ""
  #  nome_macchinario: Logicat_lavorazione_telaini_241990100
  #  nome_pezzo: verniciatura_polvere_sifone
    #Aprire iframe del produttore

  - id: Lasit_Mikromark_G3_NP115874
    rdp_enabled: false
    smb_host: 10.0.0.237
    smb_share: logs
    log_path: pezzi.log
    username: LASER
    password: laser
    domain:
    nome_macchinario: Lasit_Mikromark_G3_NP115874
    nome_pezzo: incisione_laser
    #No pass di admin, no RDP per ora, cavo crimpato male

  - id: Lasit_Rotomark_NP114459
    rdp_enabled: false
    smb_host: 10.0.0.236
    smb_share: logs
    log_path: pezzi.log
    username: LASER
    password: laser
    domain:
    nome_macchinario: Lasit_Rotomark_NP114459
    nome_pezzo: incisione_laser_pulsante_ottone_cromato
    #No pass di admin, no RDP per ora

  - id: DVK_asservimento_LR_MATE_200iD
    rdp_enabled: true
    pingable: true
    smb_host: 10.0.0.224
    smb_share: logs
    log_path: pezzi.log
    username: SPECIALVIDEO
    password: dvk
    domain: "catis.local"
    nome_macchinario: DVK_asservimento_LR_MATE_200iD
    nome_pezzo: inserimento_rubinetto_acqua_in_ottone

  - id: DVK_121120-886
    rdp_enabled: true
    pingable: true
    smb_host: 10.0.0.222
    smb_share: logs
    log_path: pezzi.log
    username: DVK
    password: dvk
    domain: "catis.local"
    nome_macchinario: DVK_121120-886
    nome_pezzo: filettatura_rubinetto_acqua_in_ottone

  - id: Concentratore_Black_White
    rdp_enabled: true
    pingable: false
    smb_host: 213.233.54.76:43234
    smb_share: logs
    log_path: pezzi.log
    username: blackwhite
    password: "YUIUrew54$8R4"
    domain: "CATIS"
    nome_macchinario: "Concentratore Black&White"
    nome_pezzo: concentratore
    # Solo RDP (porta 43234)

  - id: TORNOS_T1_Delta_1204
    rdp_enabled: false
    smb_host: 10.0.0.???
    smb_share: logs
    log_path: pezzi.log
    username:
    password: 
    domain: ""
    nome_macchinario: TORNOS_T1_Delta_1204
    nome_pezzo: tornitura_asta_ottone

  - id: HYUNDAI_WIA_kit_450
    rdp_enabled: false
    smb_host: 10.0.0.???
    smb_share: logs
    log_path: pezzi.log
    username:
    password: 
    domain: "catis.local"
    nome_macchinario: HYUNDAI_WIA_kit_450
    nome_pezzo: tornitura_rondella_in_ottone

  - id: HYUNDAI_WIA_kit_4500
    rdp_enabled: false
    smb_host: 10.0.0.???
    smb_share: logs
    log_path: pezzi.log
    username:
    password: 
    domain: "catis.local"
    nome_macchinario: HYUNDAI_WIA_kit_4500
    nome_pezzo: tornitura_chiavarda_in_ottone

  - id: SCHMALZ_jumboflex
    rdp_enabled: false
    smb_host: 10.0.0.???
    smb_share: logs
    log_path: pezzi.log
    username:
    password: 
    domain: "catis.local"
    nome_macchinario: SCHMALZ_jumboflex
    nome_pezzo: ore_di_utilizzo
    #Contare le ore di utilizzo sulla base dell'assorbimento elettrico, @martinelli

      
   
#OK -----------------------------------------


    
